# Generated by Django 3.1.4 on 2021-01-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileapp',
            name='picture',
            field=models.CharField(default='https://pbs.twimg.com/profile_images/1069226824046190592/FWqoiqOa_400x400.jpg', max_length=120),
        ),
    ]
