# Generated by Django 3.1.4 on 2021-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0002_profileapp_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileapp',
            name='gender',
            field=models.CharField(max_length=60),
        ),
    ]
